//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.18 at 11:33:26 AM EEST 
//


package com.example.service.openweathermap.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for metaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="metaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lastupdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="calctime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nextupdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metaType", propOrder = {
    "lastupdate",
    "calctime",
    "nextupdate"
})
public class MetaType {

    @XmlElement(required = true)
    protected String lastupdate;
    @XmlElement(required = true)
    protected String calctime;
    @XmlElement(required = true)
    protected String nextupdate;

    /**
     * Gets the value of the lastupdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastupdate() {
        return lastupdate;
    }

    /**
     * Sets the value of the lastupdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastupdate(String value) {
        this.lastupdate = value;
    }

    /**
     * Gets the value of the calctime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalctime() {
        return calctime;
    }

    /**
     * Sets the value of the calctime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalctime(String value) {
        this.calctime = value;
    }

    /**
     * Gets the value of the nextupdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextupdate() {
        return nextupdate;
    }

    /**
     * Sets the value of the nextupdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextupdate(String value) {
        this.nextupdate = value;
    }

}
