//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.18 at 11:33:26 AM EEST 
//


package com.example.service.openweathermap.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.common.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Weatherdata_QNAME = new QName("", "weatherdata");
    private final static QName _LocationTypeCountry_QNAME = new QName("", "country");
    private final static QName _LocationTypeTimezone_QNAME = new QName("", "timezone");
    private final static QName _LocationTypeName_QNAME = new QName("", "name");
    private final static QName _LocationTypeLocation_QNAME = new QName("", "location");
    private final static QName _LocationTypeType_QNAME = new QName("", "type");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.common.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TimeType }
     * 
     */
    public TimeType createTimeType() {
        return new TimeType();
    }

    /**
     * Create an instance of {@link WeatherdataType }
     * 
     */
    public WeatherdataType createWeatherdataType() {
        return new WeatherdataType();
    }

    /**
     * Create an instance of {@link TemperatureType }
     * 
     */
    public TemperatureType createTemperatureType() {
        return new TemperatureType();
    }

    /**
     * Create an instance of {@link HumidityType }
     * 
     */
    public HumidityType createHumidityType() {
        return new HumidityType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link ForecastType }
     * 
     */
    public ForecastType createForecastType() {
        return new ForecastType();
    }

    /**
     * Create an instance of {@link SymbolType }
     * 
     */
    public SymbolType createSymbolType() {
        return new SymbolType();
    }

    /**
     * Create an instance of {@link SunType }
     * 
     */
    public SunType createSunType() {
        return new SunType();
    }

    /**
     * Create an instance of {@link WindDirectionType }
     * 
     */
    public WindDirectionType createWindDirectionType() {
        return new WindDirectionType();
    }

    /**
     * Create an instance of {@link PrecipitationType }
     * 
     */
    public PrecipitationType createPrecipitationType() {
        return new PrecipitationType();
    }

    /**
     * Create an instance of {@link PressureType }
     * 
     */
    public PressureType createPressureType() {
        return new PressureType();
    }

    /**
     * Create an instance of {@link MetaType }
     * 
     */
    public MetaType createMetaType() {
        return new MetaType();
    }

    /**
     * Create an instance of {@link CloudsType }
     * 
     */
    public CloudsType createCloudsType() {
        return new CloudsType();
    }

    /**
     * Create an instance of {@link WindSpeedType }
     * 
     */
    public WindSpeedType createWindSpeedType() {
        return new WindSpeedType();
    }

    /**
     * Create an instance of {@link TimeType.Precipitation }
     * 
     */
    public TimeType.Precipitation createTimeTypePrecipitation() {
        return new TimeType.Precipitation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WeatherdataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "weatherdata")
    public JAXBElement<WeatherdataType> createWeatherdata(WeatherdataType value) {
        return new JAXBElement<WeatherdataType>(_Weatherdata_QNAME, WeatherdataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country", scope = LocationType.class)
    public JAXBElement<String> createLocationTypeCountry(String value) {
        return new JAXBElement<String>(_LocationTypeCountry_QNAME, String.class, LocationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "timezone", scope = LocationType.class)
    public JAXBElement<String> createLocationTypeTimezone(String value) {
        return new JAXBElement<String>(_LocationTypeTimezone_QNAME, String.class, LocationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name", scope = LocationType.class)
    public JAXBElement<String> createLocationTypeName(String value) {
        return new JAXBElement<String>(_LocationTypeName_QNAME, String.class, LocationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "location", scope = LocationType.class)
    public JAXBElement<LocationType> createLocationTypeLocation(LocationType value) {
        return new JAXBElement<LocationType>(_LocationTypeLocation_QNAME, LocationType.class, LocationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type", scope = LocationType.class)
    public JAXBElement<String> createLocationTypeType(String value) {
        return new JAXBElement<String>(_LocationTypeType_QNAME, String.class, LocationType.class, value);
    }

}
